site_name: QuestList

nav:
  - "Home": index.md
  - "Terms of Use": terms.md
theme:
  name: material
  logo: check_logo.svg
  favicon: check_logo.svg
  icon:
    repo: fontawesome/brands/github-alt
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.indexes
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.tooltips
    
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: "cyan"
      accent: "blue"
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: "cyan"
      accent: "blue"
  
markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.magiclink
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details:
  - pymdownx.superfences
  - pymdownx.blocks.tab:
      alternate_style: true
  - pymdownx.mark
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright:
  "Copyright &copy; 2025 <a href='https://www.QuestList.net/'  target='_blank' rel='noopener'>Ching-Yin Ng</a>"

plugins:
  - search
  - meta